name: Man10CheckPoint
version: '${version}'
main: tororo1066.man10checkpoint.Man10CheckPoint
api-version: 1.17

commands:
  mcp:

permissions:
  mcp.op:
    default: op
  mcp.user:

author: tororo_1066
